# Generated by Django 4.0.3 on 2022-04-09 22:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myRateit', '0002_alter_profile_profile_image_project_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='link',
            field=models.CharField(default='/', max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='votes',
            field=models.ManyToManyField(default=0, related_name='projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
