# Generated by Django 4.0.3 on 2022-04-10 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myRateit', '0003_alter_project_link_alter_project_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
