# Generated by Django 4.0.3 on 2022-04-11 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myRateit', '0004_project_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.CharField(max_length=1000),
        ),
    ]
